// app/routes/about.js -- import and export statements generated by ember when route was generated. This backend/route handler pairs with app/templates/about.hbs
import Ember from 'ember';

// the export statement 
export default Ember.Route.extend({
});
